use crate::handlers;
use crate::middleware::auth::AuthMiddleware;
use actix_web::{HttpResponse, web};

pub fn scoped_config(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::scope("/auth")
            .service(web::resource("/register").route(web::post().to(handlers::auth::register)))
            .service(web::resource("/login").route(web::post().to(handlers::auth::login)))
            .service(
                web::resource("/resend-verification")
                    .route(web::get().to(handlers::auth::resend_verification)),
            )
            .service(web::resource("/verify").route(web::post().to(handlers::auth::verify_email))),
    )
    .service(
        web::scope("/users")
            .service(
                web::resource("")
                    .route(web::get().to(handlers::users::index))
                    .route(web::head().to(HttpResponse::MethodNotAllowed)),
            )
            .service(
                web::resource("/{id}/toggle-active")
                    .wrap(AuthMiddleware)
                    .route(web::post().to(handlers::users::toggle_user_active)),
            ),
    )
    .service(
        web::scope("/contributions")
            .service(
                web::resource("")
                    .route(
                        web::post()
                            .to(handlers::contributions::create)
                            .wrap(AuthMiddleware),
                    )
                    .route(web::get().to(handlers::contributions::all))
                    .route(web::head().to(HttpResponse::MethodNotAllowed)),
            )
            .service(
                web::resource("/user")
                    .route(
                        web::get()
                            .to(handlers::contributions::get_user_contributions)
                            .wrap(AuthMiddleware),
                    )
                    .route(web::head().to(HttpResponse::MethodNotAllowed)),
            )
            .service(
                web::resource("/{id}")
                    .route(web::get().to(handlers::contributions::get_contribution))
                    .route(
                        web::delete()
                            .to(handlers::contributions::delete)
                            .wrap(AuthMiddleware),
                    )
                    .route(
                        web::put()
                            .to(handlers::contributions::update)
                            .wrap(AuthMiddleware),
                    )
                    .route(web::head().to(HttpResponse::MethodNotAllowed)),
            ),
    )
    .service(
        web::scope("/payments")
            .wrap(AuthMiddleware)
            .service(
                web::resource("")
                    .route(web::get().to(handlers::payments::all))
                    .route(web::post().to(handlers::payments::create))
                    .route(web::head().to(HttpResponse::MethodNotAllowed)),
            )
            .service(
                web::resource("/{id}")
                    .route(web::get().to(handlers::payments::get_payment))
                    .route(web::delete().to(handlers::payments::delete))
                    .route(web::put().to(handlers::payments::update))
                    .route(web::head().to(HttpResponse::MethodNotAllowed)),
            )
            .service(
                web::resource("/user/{user_id}")
                    .route(web::get().to(handlers::payments::get_user_payments))
                    .route(web::head().to(HttpResponse::MethodNotAllowed)),
            ),
    )
    .service(
        web::scope("/announcements")
            .wrap(AuthMiddleware)
            .service(
                web::resource("")
                    .route(web::get().to(handlers::announcements::all))
                    .route(web::post().to(handlers::announcements::create))
                    .route(web::head().to(HttpResponse::MethodNotAllowed)),
            )
            .service(
                web::resource("/{id}")
                    .route(web::get().to(handlers::announcements::get_announcement))
                    .route(web::delete().to(handlers::announcements::delete))
                    .route(web::put().to(handlers::announcements::update))
                    .route(web::head().to(HttpResponse::MethodNotAllowed)),
            ),
    )
    .service(
        web::scope("/photos")
            .wrap(AuthMiddleware)
            .service(
                web::resource("")
                    .route(web::get().to(handlers::photos::all))
                    .route(web::post().to(handlers::photos::create))
                    .route(web::head().to(HttpResponse::MethodNotAllowed)),
            )
            .service(
                web::resource("/{id}")
                    .route(web::get().to(handlers::photos::get_photo))
                    .route(web::delete().to(handlers::photos::delete))
                    .route(web::put().to(handlers::photos::update))
                    .route(web::head().to(HttpResponse::MethodNotAllowed)),
            ),
    );
}
